---
language: node_js
node_js:
  - "6"

sudo: required
dist: trusty

branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm install -g npm@5
  - npm config set spin false
